# Generated by Django 4.1 on 2022-09-09 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('issue_number', models.IntegerField(null=True)),
                ('sale_date', models.DateField()),
                ('synopsis', models.CharField(max_length=100)),
                ('cover_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ComicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('founded', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.creator')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='creators',
            field=models.ManyToManyField(related_name='team_creator', through='longboxdapi.TeamCreator', to='longboxdapi.creator'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('favorite', models.BooleanField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.collector')),
            ],
        ),
        migrations.CreateModel(
            name='ComicTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.comic')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.team')),
            ],
        ),
        migrations.CreateModel(
            name='ComicCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.comic')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.creator')),
            ],
        ),
        migrations.CreateModel(
            name='ComicCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.character')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.comic')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='characters',
            field=models.ManyToManyField(related_name='character_in_issue', through='longboxdapi.ComicCharacter', to='longboxdapi.character'),
        ),
        migrations.AddField(
            model_name='comic',
            name='credits',
            field=models.ManyToManyField(related_name='comic_creator', through='longboxdapi.ComicCreator', to='longboxdapi.creator'),
        ),
        migrations.AddField(
            model_name='comic',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.publisher'),
        ),
        migrations.AddField(
            model_name='comic',
            name='teams',
            field=models.ManyToManyField(related_name='team_in_comic', through='longboxdapi.ComicTeam', to='longboxdapi.team'),
        ),
        migrations.AddField(
            model_name='comic',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.comictype'),
        ),
        migrations.CreateModel(
            name='CharacterTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.character')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.team')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.character')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longboxdapi.creator')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='creators',
            field=models.ManyToManyField(related_name='caracter_creator', through='longboxdapi.CharacterCreator', to='longboxdapi.creator'),
        ),
        migrations.AddField(
            model_name='character',
            name='teams',
            field=models.ManyToManyField(related_name='team', through='longboxdapi.CharacterTeam', to='longboxdapi.team'),
        ),
    ]
