# Generated by Django 4.1 on 2022-09-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longboxdapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='type',
            new_name='comic_type',
        ),
    ]
