# Generated by Django 4.1 on 2022-09-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longboxdapi', '0002_rename_type_comic_comic_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='publisher_id',
            new_name='publisher',
        ),
    ]
