# Generated by Django 4.1 on 2022-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longboxdapi', '0003_rename_publisher_id_comic_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='collection',
            field=models.ManyToManyField(related_name='comic_in_collection', to='longboxdapi.comic'),
        ),
        migrations.AddField(
            model_name='collector',
            name='wishlist',
            field=models.ManyToManyField(related_name='comic_in_wishlist', to='longboxdapi.comic'),
        ),
    ]
