# Generated by Django 4.1 on 2022-09-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longboxdapi', '0004_collector_collection_collector_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=500),
        ),
    ]
