# Generated by Django 4.1 on 2022-09-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longboxdapi', '0005_alter_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='favorite',
        ),
    ]
