# Generated by Django 4.1 on 2022-09-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longboxdapi', '0006_remove_review_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='longboxdapi.comic'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='longboxdapi.collector'),
        ),
    ]
